---
- name: Update and upgrade all hosts
  hosts: sol_system
  user: knifey
  tasks:
    - name: Update and upgrade via yum with updating cache
      become: true
      ansible.builtin.yum:
          name: "*"
          update_cache: yes
          state: latest
