---
- name: Update and upgrade all hosts
  hosts: sol_system
  user: ubuntu
  tasks:
    - name: Update and upgrade via apt with updating cache
      become: true
      ansible.builtin.apt:
          name: "*"
          update_cache: yes
          state: latest
