{
 "title": "Pi Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Raspberry Pi Temperatures History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "rpi_cpu_temperature_celsius" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"prometheus\", instance=\"mercury.knifey:9100\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"prometheus\", instance=\"venus.knifey:9100\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"prometheus\", instance=\"earth.knifey:9100\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"prometheus\", instance=\"mars.knifey:9100\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes{instance=\"mercury.knifey:9100\"}/node_memory_MemTotal_bytes{instance=\"mercury.knifey:9100\"})*100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(node_memory_MemFree_bytes{instance=\"venus.knifey:9100\"}/node_memory_MemTotal_bytes{instance=\"venus.knifey:9100\"})*100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(node_memory_MemFree_bytes{instance=\"earth.knifey:9100\"}/node_memory_MemTotal_bytes{instance=\"earth.knifey:9100\"})*100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(node_memory_MemFree_bytes{instance=\"mars.knifey:9100\"}/node_memory_MemTotal_bytes{instance=\"mars.knifey:9100\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-(node_filesystem_free_bytes{device=\"/dev/mapper/fedora-root\", instance=\"mercury.knifey:9100\"}/node_filesystem_size_bytes{device=\"/dev/mapper/fedora-root\", instance=\"mercury.knifey:9100\", mountpoint=\"/\"}))*100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(1-(node_filesystem_free_bytes{device=\"/dev/mapper/fedora-root\", instance=\"venus.knifey:9100\"}/node_filesystem_size_bytes{device=\"/dev/mapper/fedora-root\", instance=\"venus.knifey:9100\", mountpoint=\"/\"}))*100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(1-(node_filesystem_free_bytes{device=\"/dev/mapper/fedora-root\", instance=\"earth.knifey:9100\"}/node_filesystem_size_bytes{device=\"/dev/mapper/fedora-root\", instance=\"earth.knifey:9100\", mountpoint=\"/\"}))*100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(1-(node_filesystem_free_bytes{device=\"/dev/mapper/fedora-root\", instance=\"mars.knifey:9100\"}/node_filesystem_size_bytes{device=\"/dev/mapper/fedora-root\", instance=\"mars.knifey:9100\", mountpoint=\"/\"}))*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "wlan0 status",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "wlan0",
     "crit": 100,
     "disabledValue": "0",
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "node_network_up{device=\"wlan0\", job=\"prometheus\", instance=\"mercury.knifey:9100\"} OR on() vector(100)",
     "legendFormat": "{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 50
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "node_network_up{device=\"wlan0\", job=\"prometheus\", instance=\"venus.knifey:9100\"} OR on() vector(100)",
     "legendFormat": "{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "node_network_up{device=\"wlan0\", job=\"prometheus\", instance=\"earth.knifey:9100\"} OR on() vector(100)",
     "legendFormat": "{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "node_network_up{device=\"wlan0\", job=\"prometheus\", instance=\"mars.knifey:9100\"} OR on() vector(100)",
     "legendFormat": "{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}